[package]
name = "sqlx-praxis"
version = "0.1.1"
edition = "2018"

[dependencies]
tokio = { version = "1.12", features = ["full"] }
sqlx = { version = "0.5", features = [ "sqlite", "runtime-tokio-rustls" ] }